#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Generate a reusable TRAINED gf16 model + eval set as committed artifacts.
#
# Trains a 2-layer MLP (15 PCA -> 15 ReLU hidden -> 10) on sklearn digits, quantizes
# the weights AND the held-out test inputs to gf16, and writes them to
# test/gf16_model/ as plain gf16-code files. The point: the trained model and its
# eval set become standalone artifacts that test/run_trained_gf16_eval.py replays
# through the actual RTL WITHOUT sklearn -- the "external lever" for the Defect-1
# task number, materialized and reproducible. Deterministic (fixed seed).
#
# Layout written:
#   gf16_model/W1.mem        15 lines x 16 gf16 codes  (hidden weights incl. bias col)
#   gf16_model/W2.mem        10 lines x 16 gf16 codes  (output weights incl. bias col)
#   gf16_model/eval_X.mem    N lines  x 16 gf16 codes  (test inputs: 15 PCA + bias=1.0)
#   gf16_model/eval_y.txt    N lines  (true labels)
#   gf16_model/README.md     provenance + architecture + how to run
import os, sys
try:
    import numpy as np
    from sklearn.datasets import load_digits
    from sklearn.decomposition import PCA
    from sklearn.preprocessing import StandardScaler
    from sklearn.neural_network import MLPClassifier
    from sklearn.model_selection import train_test_split
except Exception as e:
    print("needs numpy + scikit-learn (", e, ")"); sys.exit(1)

HERE=os.path.dirname(os.path.abspath(__file__)); OUT=os.path.join(HERE,"gf16_model")
BIAS,HID,CLS=31,15,10; SEED=7
def encode(x):
    if x==0: return 0
    s=1 if x<0 else 0; ax=abs(float(x)); e=BIAS
    while ax>=2.0**(e-BIAS+1) and e<62: e+=1
    while ax<2.0**(e-BIAS) and e>1: e-=1
    m=int(round((ax/2.0**(e-BIAS)-1.0)*512))
    if m>=512: m=0; e+=1
    if e>=63: return (s<<15)|(63<<9)
    if e<1: return 0
    return (s<<15)|(e<<9)|m
ONE=encode(1.0)

def row(codes): return " ".join("%04x"%c for c in codes)

def main():
    os.makedirs(OUT,exist_ok=True)
    d=load_digits()
    Xtr,Xte,ytr,yte=train_test_split(d.data,d.target,test_size=0.25,random_state=SEED,stratify=d.target)
    sc=StandardScaler().fit(Xtr); pca=PCA(n_components=HID,random_state=SEED).fit(sc.transform(Xtr))
    Ztr=pca.transform(sc.transform(Xtr)); Zte=pca.transform(sc.transform(Xte))
    clf=MLPClassifier(hidden_layer_sizes=(HID,),activation='relu',max_iter=800,
                      random_state=SEED,alpha=1e-3).fit(Ztr,ytr)
    float_acc=(clf.predict(Zte)==yte).mean()
    W1=clf.coefs_[0]; b1=clf.intercepts_[0]; W2=clf.coefs_[1]; b2=clf.intercepts_[1]
    W1q=[[encode(W1[k,j]) for k in range(HID)]+[encode(b1[j])] for j in range(HID)]
    W2q=[[encode(W2[k,o]) for k in range(HID)]+[encode(b2[o])] for o in range(CLS)]
    Xq=[[encode(Zte[i,k]) for k in range(HID)]+[ONE] for i in range(len(Zte))]

    open(os.path.join(OUT,"W1.mem"),"w").write("\n".join(row(r) for r in W1q)+"\n")
    open(os.path.join(OUT,"W2.mem"),"w").write("\n".join(row(r) for r in W2q)+"\n")
    open(os.path.join(OUT,"eval_X.mem"),"w").write("\n".join(row(r) for r in Xq)+"\n")
    open(os.path.join(OUT,"eval_y.txt"),"w").write("\n".join(str(int(y)) for y in yte)+"\n")
    open(os.path.join(OUT,"README.md"),"w").write(f"""# Trained gf16 model + eval set (sklearn digits)

Reusable artifact for the Defect-1 (gf16_mul) task-impact study -- the "external
lever" beyond the synthetic proxy, materialized so it can be replayed without
retraining. All values are gf16 codes [S(1) E(6) M(9)], bias 31.

## Architecture
2-layer MLP: 15 PCA features -> 15 ReLU hidden -> 10 classes (logistic output).
Each layer is one 16-element `dot16` (15 weights + 1 bias column; inputs carry a
trailing bias term = gf16 1.0 = 0x{ONE:04x}). ReLU between layers (negative gf16
code -> 0). Trained on sklearn `digits` (8x8, 10 classes), seed {SEED}.

## Files
- `W1.mem`   {HID} hidden units x 16 gf16 weight codes
- `W2.mem`   {CLS} classes x 16 gf16 weight codes
- `eval_X.mem`  {len(Xq)} test inputs x 16 gf16 codes (15 PCA + bias)
- `eval_y.txt`  {len(Xq)} true labels

## Provenance
float (sklearn) test accuracy: {100*float_acc:.2f}%
Generated by `test/gen_gf16_model.py` (deterministic). Replay through the actual
RTL with `test/run_trained_gf16_eval.py` (no sklearn needed) -> reports shipped vs
corrected (gf16_v2) accuracy + the Defect-1 argmax-flip number.
""")
    print(f"wrote {OUT}/ : W1({HID}x16) W2({CLS}x16) eval_X({len(Xq)}x16) eval_y  | float acc {100*float_acc:.2f}%")
    return 0

if __name__=="__main__":
    sys.exit(main())
