#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Generator for correct gfN_add units, generalizing the exhaustively-verified
# gf8_add (proper float add: G guard bits, sticky-capturing alignment, priority
# renormalize, round-to-nearest ties-to-even, signed exponent with correct
# under/overflow). The previous gf12_add was broken: final_exp was only E bits so
# the underflow test final_exp[E-1] wrongly flushed every valid exponent >= 2^(E-1)
# to zero (1.0+1.0 -> exp 8 -> 0), and the normal-case mantissa slice was shifted.
#
# Validation: this generator reproduces gf8_add; `python3 test/gen_gf_add_fix.py
# --check-gf8` regenerates gf8_add and you can re-run test/gf8_exhaustive.py to
# confirm 65536/65536 still pass (the generator == the hand-verified module).

import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, "..", "src")
G = 3  # guard bits below the significand

# name: (total, E, M). Special constants are DERIVED (Inf = exp-all-ones & mant==0;
# NaN = exp-all-ones & mant!=0; +-0 = +-(exp0,mant0)). The gf12 constants hardcoded
# previously were wrong (its "Inf" 0x700 is exp=14, a finite value, not exp=15).
RUNGS = {
    "gf8":  (8,  3, 4),
    "gf12": (12, 4, 7),
    "gf20": (20, 7, 12),
    "gf24": (24, 9, 14),
    "gf32": (32, 12, 19),
    "gf64": (64, 24, 39),
    "gf128": (128, 48, 79),
}
# NB: gf16_add is intentionally NOT regenerated -- it is the silicon-[Verified]
# rung; its source must match the fabricated die. Its known legacy imprecision is
# documented in docs/GF_ARITH_FINDINGS.md.

def specials(total, E, M):
    emax = (1 << E) - 1
    pinf = emax << M
    sgn  = 1 << (total - 1)
    lit  = lambda v: "%d'h%X" % (total, v)
    # NAN, PINF, NINF, ZERO, NEGZERO
    return lit(sgn | pinf | 1), lit(pinf), lit(sgn | pinf), lit(0), lit(sgn)

def norm_chain(M, E):
    """Emit the priority renormalize if/else chain for sum_m, leading bit p."""
    MG = M + G
    top = MG + 1                      # carry position
    lines = []
    first = True
    for p in range(top, 0, -1):       # p = top .. 1 ; p==0 is the final else
        kw = "if" if first else "else if"
        first = False
        adj = p - MG                  # exponent adjustment (+1 carry, 0 normal, -k)
        body = []
        if adj > 0:
            body.append(f"rexp = rexp + {E+2}'sd{adj};")
        elif adj < 0:
            body.append(f"rexp = rexp - {E+2}'sd{-adj};")
        # mantissa (M bits) + guard/round/sticky
        if p >= M:
            body.append(f"mant_out = sum_m[{p-1}:{p-M}];")
            g  = f"sum_m[{p-M-1}]" if p-M-1 >= 0 else "1'b0"
            rb = f"sum_m[{p-M-2}]" if p-M-2 >= 0 else "1'b0"
            if p-M-3 >= 0:
                s = f"(|sum_m[{p-M-3}:0]) | sticky_shift"
            else:
                s = "sticky_shift"
            body.append(f"guard = {g}; round_b = {rb}; sticky = {s};")
        else:  # p < M : left-justify the available bits, pad zeros
            if p == 0:
                body.append(f"mant_out = {M}'d0;")
            else:
                body.append(f"mant_out = {{sum_m[{p-1}:0], {M-p}'d0}};")
            body.append("guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;")
        lines.append(f"                {kw} (sum_m[{p}]) begin")
        for b in body:
            lines.append(f"                    {b}")
        lines.append("                end")
    # final else: p == 0
    lines.append("                else begin")
    lines.append(f"                    mant_out = {M}'d0;")
    lines.append("                    guard = 1'b0; round_b = 1'b0; sticky = sticky_shift;")
    lines.append("                end")
    return "\n".join(lines)

TEMPLATE = """// SPDX-License-Identifier: Apache-2.0
// t27/rtl_gen/{name}_add.v
// GoldenFloat{total} Addition Unit -- [S(1) | E({E}) | M({M})], bias 2^(E-1)-1.
// value = (-1)^S (1 + M/2^{M}) 2^(E-bias).
//
// Generated by test/gen_gf_add_fix.py (generalizes the exhaustively-verified
// gf8_add). Proper float add: significands carry {G} guard bits, alignment captures
// a sticky bit, the post-add leading 1 is found by priority and renormalized, and
// the {M}-bit mantissa is rounded to nearest, ties-to-even. The running exponent is
// SIGNED and wide enough to tell underflow (exp<0) from a valid large exponent --
// the previous unit flushed valid exponents >= 2^(E-1) to zero. Verified by
// test/gf_arith_xcheck.py and test/gf_add_sweep.py.

`default_nettype none
module {name}_add (
    input  wire [{hi}:0] a,
    input  wire [{hi}:0] b,
    output reg  [{hi}:0] result
);

    localparam [{ehi}:0] EXP_MAX = {emax};
    localparam signed [{esw}:0] EXP_MAX_S = {emax_s};

    wire             sign_a = a[{hi}];
    wire [{ehi}:0]   exp_a  = a[{ehia}:{mw}];
    wire [{mhi}:0]   mant_a = a[{mhi}:0];
    wire             sign_b = b[{hi}];
    wire [{ehi}:0]   exp_b  = b[{ehia}:{mw}];
    wire [{mhi}:0]   mant_b = b[{mhi}:0];

    wire is_zero_a = (exp_a == {ez}) && (mant_a == {mz});
    wire is_zero_b = (exp_b == {ez}) && (mant_b == {mz});
    wire is_inf_a  = (exp_a == EXP_MAX) && (mant_a == {mz});
    wire is_inf_b  = (exp_b == EXP_MAX) && (mant_b == {mz});
    wire is_nan_a  = (exp_a == EXP_MAX) && (mant_a != {mz});
    wire is_nan_b  = (exp_b == EXP_MAX) && (mant_b != {mz});

    wire a_larger = (exp_a > exp_b) || ((exp_a == exp_b) && (mant_a >= mant_b));

    reg        big_sign, small_sign, result_sign;
    reg [{ehi}:0] big_exp, small_exp;
    reg [{mhi}:0] big_m, small_m;
    reg [{ewhi}:0] big_ext, small_ext, shifted;   // {{1, mant, {G} guard bits}}
    reg [{shw}:0]  shamt;
    reg            sticky_shift;
    reg [{sumhi}:0] sum_m;                          // room for add carry
    reg signed [{esw}:0] rexp;
    reg [{mhi}:0]  mant_out;
    reg [{mw}:0]   mant_rounded;                    // M+1 bits, catches overflow
    reg            guard, round_b, sticky, round_up;

    always @(*) begin
        big_sign = 0; small_sign = 0; result_sign = 0;
        big_exp = 0; small_exp = 0; big_m = 0; small_m = 0;
        big_ext = 0; small_ext = 0; shifted = 0; shamt = 0; sticky_shift = 0;
        sum_m = 0; rexp = 0; mant_out = 0; mant_rounded = 0;
        guard = 0; round_b = 0; sticky = 0; round_up = 0;

        if (is_nan_a || is_nan_b)
            result = {NAN};
        else if (is_inf_a && is_inf_b && (sign_a != sign_b))
            result = {NAN};
        else if (is_inf_a)
            result = sign_a ? {NINF} : {PINF};
        else if (is_inf_b)
            result = sign_b ? {NINF} : {PINF};
        else if (is_zero_a && is_zero_b)
            result = {ZERO};
        else if (is_zero_a)
            result = b;
        else if (is_zero_b)
            result = a;
        else begin
            if (a_larger) begin
                big_sign = sign_a; big_exp = exp_a; big_m = mant_a;
                small_sign = sign_b; small_exp = exp_b; small_m = mant_b;
            end else begin
                big_sign = sign_b; big_exp = exp_b; big_m = mant_b;
                small_sign = sign_a; small_exp = exp_a; small_m = mant_a;
            end

            big_ext   = {{1'b1, big_m,   {G}'b0}};
            small_ext = {{1'b1, small_m, {G}'b0}};
            shamt     = big_exp - small_exp;

            if (shamt >= {ewbits})
                begin shifted = 0; sticky_shift = |small_ext; end
            else begin
                shifted = small_ext >> shamt;
                sticky_shift = |(small_ext & (({ewbits}'d1 << shamt) - {ewbits}'d1));
            end

            result_sign = big_sign;
            rexp = $signed({{{epad}'b0, big_exp}});

            if (big_sign == small_sign)
                sum_m = {{1'b0, big_ext}} + {{1'b0, shifted}};
            else
                sum_m = {{1'b0, big_ext}} - {{1'b0, shifted}};

            if (sum_m == 0) begin
                result = {ZERO};
            end else begin
{NORMCHAIN}

                round_up     = guard && (round_b || sticky || mant_out[0]);
                mant_rounded = {{1'b0, mant_out}} + (round_up ? {mw1}'d1 : {mw1}'d0);
                if (mant_rounded[{mw}]) begin
                    rexp     = rexp + {esw1}'sd1;
                    mant_out = {mz};
                end else begin
                    mant_out = mant_rounded[{mhi}:0];
                end

                if (rexp < 0)
                    result = result_sign ? {NEGZERO} : {ZERO};
                else if (rexp >= EXP_MAX_S)
                    result = result_sign ? {NINF} : {PINF};
                else if (rexp == 0 && mant_out == {mz})
                    result = result_sign ? {NEGZERO} : {ZERO};
                else
                    result = {{result_sign, rexp[{ehi}:0], mant_out}};
            end
        end
    end

endmodule
"""

def emit(name, write=True):
    total, E, M = RUNGS[name]
    NAN, PINF, NINF, ZERO, NEGZERO = specials(total, E, M)
    EW = 1 + M + G
    f = TEMPLATE.format(
        name=name, total=total, E=E, M=M, G=G,
        hi=total - 1, ehi=E - 1, mhi=M - 1, mw=M, ehia=total - 2,
        emax=("%d'd%d" % (E, 2 ** E - 1)), emax_s="%d'sd%d" % (E + 2, 2 ** E - 1),
        esw=E + 1, esw1=E + 2, epad=2, mw1=M + 1,
        ez="%d'd0" % E, mz="%d'd0" % M,
        ewhi=EW - 1, ewbits=EW, shw=E, sumhi=M + G + 1,
        NAN=NAN, PINF=PINF, NINF=NINF, ZERO=ZERO, NEGZERO=NEGZERO,
        NORMCHAIN=norm_chain(M, E),
    )
    if write:
        path = os.path.join(SRC, name + "_add.v")
        with open(path, "w") as fh:
            fh.write(f)
        print("wrote", path)
    return f

if __name__ == "__main__":
    if "--check-gf8" in sys.argv:
        emit("gf8")            # overwrite gf8_add with the generated version
    else:
        for n in RUNGS:
            if n == "gf8":     # gf8_add is hand-written + exhaustively verified
                continue
            emit(n)
