#!/usr/bin/env python3
"""Correct GoldenFloat multiplier generator (fixes the systemic MSB-position bug).
Universal template: product of two (M+1)-bit mantissas is 2M+2 bits [2M+1:0];
leading 1 at bit 2M+1 (va*vb in [2,4) -> exp+1) or bit 2M ([1,2)). Round-half-up.
Emits gf{bits}_mul.v for each format below."""
import sys

# bits: (EBITS, MBITS, BIAS)
FMT = {
    4:(1,2,0), 8:(3,4,3), 12:(4,7,7), 16:(6,9,31), 20:(7,12,63),
    24:(9,14,255), 32:(12,19,2047), 64:(24,39,8388607),
    128:(48,79,140737488355327), 256:(97,158,79228162514264337593543950335),
}

def gen(bits, E, M, BIAS):
    N=bits; P=2*M+2; PH=P-1                 # product width / top index
    EMAX=(1<<E)-1
    EW=E+3                                   # signed exp accumulator width
    def v(width,val): return f"{width}'d{val}"
    return f"""// SPDX-License-Identifier: Apache-2.0
// gf{N}_mul.v - GoldenFloat{N} ({1}/{E}/{M}, bias {BIAS}) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf{N}_mul (
    input  wire [{N-1}:0] a,
    input  wire [{N-1}:0] b,
    output reg  [{N-1}:0] result
);
    localparam [{E-1}:0] BIAS = {v(E,BIAS)};
    localparam [{E-1}:0] EXP_MAX = {v(E,EMAX)};

    wire             sign_a = a[{N-1}];
    wire [{E-1}:0]   exp_a  = a[{N-2}:{M}];
    wire [{M-1}:0]   mant_a = a[{M-1}:0];
    wire             sign_b = b[{N-1}];
    wire [{E-1}:0]   exp_b  = b[{N-2}:{M}];
    wire [{M-1}:0]   mant_b = b[{M-1}:0];

    wire is_zero_a = (exp_a=={v(E,0)}) && (mant_a=={v(M,0)});
    wire is_zero_b = (exp_b=={v(E,0)}) && (mant_b=={v(M,0)});
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a=={v(M,0)});
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b=={v(M,0)});
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!={v(M,0)});
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!={v(M,0)});
    wire result_sign = sign_a ^ sign_b;

    localparam [{N-1}:0] POS_INF = {{1'b0, EXP_MAX, {v(M,0)}}};
    localparam [{N-1}:0] NEG_INF = {{1'b1, EXP_MAX, {v(M,0)}}};
    localparam [{N-1}:0] QNAN    = {{1'b1, EXP_MAX, {v(M,1)}}};

    reg signed [{EW-1}:0] exp_product;
    reg [{PH}:0] mant_product;          // 2M+2 = {P}-bit product
    reg [{M}:0]  norm;                  // {{leading1, M mantissa bits}}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {{result_sign, {v(N-1,0)}}};
        else begin
            exp_product  = $signed({{ {EW-E}'b0, exp_a}}) + $signed({{ {EW-E}'b0, exp_b}}) - $signed({{ {EW-E}'b0, BIAS}});
            mant_product = {{1'b1, mant_a}} * {{1'b1, mant_b}};
            if (mant_product[{PH}]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + {EW}'sd1;
                norm  = {{1'b1, mant_product[{PH-1}:{M+1}]}};
                guard = mant_product[{M}];
            end else begin                                 // [1,2): leading 1 at bit {PH-1}
                norm  = {{1'b1, mant_product[{PH-2}:{M}]}};
                guard = mant_product[{M-1}];
            end
            if (guard) norm = norm + {M+1}'d1;
            if (norm == {M+1}'d0) exp_product = exp_product + {EW}'sd1;
            if (exp_product <= 0)
                result = {{result_sign, {v(N-1,0)}}};
            else if (exp_product >= $signed({{ {EW-E}'b0, EXP_MAX}}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {{result_sign, exp_product[{E-1}:0], norm[{M-1}:0]}};
        end
    end
endmodule
"""

if __name__=="__main__":
    only = [int(x) for x in sys.argv[1:]] or sorted(FMT)
    for bits in only:
        E,M,BIAS = FMT[bits]
        open(f"gf{bits}_mul_gen.v","w").write(gen(bits,E,M,BIAS))
        print(f"emitted gf{bits}_mul_gen.v (E={E} M={M} bias={BIAS})")
