// SPDX-License-Identifier: Apache-2.0
// gf128_mul.v - GoldenFloat128 (1/48/79, bias 140737488355327) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf128_mul (
    input  wire [127:0] a,
    input  wire [127:0] b,
    output reg  [127:0] result
);
    localparam [47:0] BIAS = 48'd140737488355327;
    localparam [47:0] EXP_MAX = 48'd281474976710655;

    wire             sign_a = a[127];
    wire [47:0]   exp_a  = a[126:79];
    wire [78:0]   mant_a = a[78:0];
    wire             sign_b = b[127];
    wire [47:0]   exp_b  = b[126:79];
    wire [78:0]   mant_b = b[78:0];

    wire is_zero_a = (exp_a==48'd0) && (mant_a==79'd0);
    wire is_zero_b = (exp_b==48'd0) && (mant_b==79'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==79'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==79'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=79'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=79'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [127:0] POS_INF = {1'b0, EXP_MAX, 79'd0};
    localparam [127:0] NEG_INF = {1'b1, EXP_MAX, 79'd0};
    localparam [127:0] QNAN    = {1'b1, EXP_MAX, 79'd1};

    reg signed [50:0] exp_product;
    reg [159:0] mant_product;          // 2M+2 = 160-bit product
    reg [79:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 127'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[159]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 51'sd1;
                norm  = {1'b1, mant_product[158:80]};
                guard = mant_product[79];
            end else begin                                 // [1,2): leading 1 at bit 158
                norm  = {1'b1, mant_product[157:79]};
                guard = mant_product[78];
            end
            if (guard) norm = norm + 80'd1;
            if (norm == 80'd0) exp_product = exp_product + 51'sd1;
            if (exp_product <= 0)
                result = {result_sign, 127'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[47:0], norm[78:0]};
        end
    end
endmodule
