// SPDX-License-Identifier: Apache-2.0
// gf12_mul.v - GoldenFloat12 (1/4/7, bias 7) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf12_mul (
    input  wire [11:0] a,
    input  wire [11:0] b,
    output reg  [11:0] result
);
    localparam [3:0] BIAS = 4'd7;
    localparam [3:0] EXP_MAX = 4'd15;

    wire             sign_a = a[11];
    wire [3:0]   exp_a  = a[10:7];
    wire [6:0]   mant_a = a[6:0];
    wire             sign_b = b[11];
    wire [3:0]   exp_b  = b[10:7];
    wire [6:0]   mant_b = b[6:0];

    wire is_zero_a = (exp_a==4'd0) && (mant_a==7'd0);
    wire is_zero_b = (exp_b==4'd0) && (mant_b==7'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==7'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==7'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=7'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=7'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [11:0] POS_INF = {1'b0, EXP_MAX, 7'd0};
    localparam [11:0] NEG_INF = {1'b1, EXP_MAX, 7'd0};
    localparam [11:0] QNAN    = {1'b1, EXP_MAX, 7'd1};

    reg signed [6:0] exp_product;
    reg [15:0] mant_product;          // 2M+2 = 16-bit product
    reg [7:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 11'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[15]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 7'sd1;
                norm  = {1'b1, mant_product[14:8]};
                guard = mant_product[7];
            end else begin                                 // [1,2): leading 1 at bit 14
                norm  = {1'b1, mant_product[13:7]};
                guard = mant_product[6];
            end
            if (guard) norm = norm + 8'd1;
            if (norm == 8'd0) exp_product = exp_product + 7'sd1;
            if (exp_product <= 0)
                result = {result_sign, 11'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[3:0], norm[6:0]};
        end
    end
endmodule
