// SPDX-License-Identifier: Apache-2.0
// gf16_mul.v - GoldenFloat16 (1/6/9, bias 31) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf16_mul (
    input  wire [15:0] a,
    input  wire [15:0] b,
    output reg  [15:0] result
);
    localparam [5:0] BIAS = 6'd31;
    localparam [5:0] EXP_MAX = 6'd63;

    wire             sign_a = a[15];
    wire [5:0]   exp_a  = a[14:9];
    wire [8:0]   mant_a = a[8:0];
    wire             sign_b = b[15];
    wire [5:0]   exp_b  = b[14:9];
    wire [8:0]   mant_b = b[8:0];

    wire is_zero_a = (exp_a==6'd0) && (mant_a==9'd0);
    wire is_zero_b = (exp_b==6'd0) && (mant_b==9'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==9'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==9'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=9'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=9'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [15:0] POS_INF = {1'b0, EXP_MAX, 9'd0};
    localparam [15:0] NEG_INF = {1'b1, EXP_MAX, 9'd0};
    localparam [15:0] QNAN    = {1'b1, EXP_MAX, 9'd1};

    reg signed [8:0] exp_product;
    reg [19:0] mant_product;          // 2M+2 = 20-bit product
    reg [9:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 15'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[19]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 9'sd1;
                norm  = {1'b1, mant_product[18:10]};
                guard = mant_product[9];
            end else begin                                 // [1,2): leading 1 at bit 18
                norm  = {1'b1, mant_product[17:9]};
                guard = mant_product[8];
            end
            if (guard) norm = norm + 10'd1;
            if (norm == 10'd0) exp_product = exp_product + 9'sd1;
            if (exp_product <= 0)
                result = {result_sign, 15'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[5:0], norm[8:0]};
        end
    end
endmodule
