// SPDX-License-Identifier: Apache-2.0
// gf20_mul.v - GoldenFloat20 (1/7/12, bias 63) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf20_mul (
    input  wire [19:0] a,
    input  wire [19:0] b,
    output reg  [19:0] result
);
    localparam [6:0] BIAS = 7'd63;
    localparam [6:0] EXP_MAX = 7'd127;

    wire             sign_a = a[19];
    wire [6:0]   exp_a  = a[18:12];
    wire [11:0]   mant_a = a[11:0];
    wire             sign_b = b[19];
    wire [6:0]   exp_b  = b[18:12];
    wire [11:0]   mant_b = b[11:0];

    wire is_zero_a = (exp_a==7'd0) && (mant_a==12'd0);
    wire is_zero_b = (exp_b==7'd0) && (mant_b==12'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==12'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==12'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=12'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=12'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [19:0] POS_INF = {1'b0, EXP_MAX, 12'd0};
    localparam [19:0] NEG_INF = {1'b1, EXP_MAX, 12'd0};
    localparam [19:0] QNAN    = {1'b1, EXP_MAX, 12'd1};

    reg signed [9:0] exp_product;
    reg [25:0] mant_product;          // 2M+2 = 26-bit product
    reg [12:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 19'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[25]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 10'sd1;
                norm  = {1'b1, mant_product[24:13]};
                guard = mant_product[12];
            end else begin                                 // [1,2): leading 1 at bit 24
                norm  = {1'b1, mant_product[23:12]};
                guard = mant_product[11];
            end
            if (guard) norm = norm + 13'd1;
            if (norm == 13'd0) exp_product = exp_product + 10'sd1;
            if (exp_product <= 0)
                result = {result_sign, 19'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[6:0], norm[11:0]};
        end
    end
endmodule
