// SPDX-License-Identifier: Apache-2.0
// gf4_mul.v - GoldenFloat4 (1/1/2, bias 0) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf4_mul (
    input  wire [3:0] a,
    input  wire [3:0] b,
    output reg  [3:0] result
);
    localparam [0:0] BIAS = 1'd0;
    localparam [0:0] EXP_MAX = 1'd1;

    wire             sign_a = a[3];
    wire [0:0]   exp_a  = a[2:2];
    wire [1:0]   mant_a = a[1:0];
    wire             sign_b = b[3];
    wire [0:0]   exp_b  = b[2:2];
    wire [1:0]   mant_b = b[1:0];

    wire is_zero_a = (exp_a==1'd0) && (mant_a==2'd0);
    wire is_zero_b = (exp_b==1'd0) && (mant_b==2'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==2'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==2'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=2'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=2'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [3:0] POS_INF = {1'b0, EXP_MAX, 2'd0};
    localparam [3:0] NEG_INF = {1'b1, EXP_MAX, 2'd0};
    localparam [3:0] QNAN    = {1'b1, EXP_MAX, 2'd1};

    reg signed [3:0] exp_product;
    reg [5:0] mant_product;          // 2M+2 = 6-bit product
    reg [2:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 3'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[5]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 4'sd1;
                norm  = {1'b1, mant_product[4:3]};
                guard = mant_product[2];
            end else begin                                 // [1,2): leading 1 at bit 4
                norm  = {1'b1, mant_product[3:2]};
                guard = mant_product[1];
            end
            if (guard) norm = norm + 3'd1;
            if (norm == 3'd0) exp_product = exp_product + 4'sd1;
            if (exp_product <= 0)
                result = {result_sign, 3'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[0:0], norm[1:0]};
        end
    end
endmodule
