// SPDX-License-Identifier: Apache-2.0
// gf64_mul.v - GoldenFloat64 (1/24/39, bias 8388607) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf64_mul (
    input  wire [63:0] a,
    input  wire [63:0] b,
    output reg  [63:0] result
);
    localparam [23:0] BIAS = 24'd8388607;
    localparam [23:0] EXP_MAX = 24'd16777215;

    wire             sign_a = a[63];
    wire [23:0]   exp_a  = a[62:39];
    wire [38:0]   mant_a = a[38:0];
    wire             sign_b = b[63];
    wire [23:0]   exp_b  = b[62:39];
    wire [38:0]   mant_b = b[38:0];

    wire is_zero_a = (exp_a==24'd0) && (mant_a==39'd0);
    wire is_zero_b = (exp_b==24'd0) && (mant_b==39'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==39'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==39'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=39'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=39'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [63:0] POS_INF = {1'b0, EXP_MAX, 39'd0};
    localparam [63:0] NEG_INF = {1'b1, EXP_MAX, 39'd0};
    localparam [63:0] QNAN    = {1'b1, EXP_MAX, 39'd1};

    reg signed [26:0] exp_product;
    reg [79:0] mant_product;          // 2M+2 = 80-bit product
    reg [39:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 63'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[79]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 27'sd1;
                norm  = {1'b1, mant_product[78:40]};
                guard = mant_product[39];
            end else begin                                 // [1,2): leading 1 at bit 78
                norm  = {1'b1, mant_product[77:39]};
                guard = mant_product[38];
            end
            if (guard) norm = norm + 40'd1;
            if (norm == 40'd0) exp_product = exp_product + 27'sd1;
            if (exp_product <= 0)
                result = {result_sign, 63'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[23:0], norm[38:0]};
        end
    end
endmodule
