// SPDX-License-Identifier: Apache-2.0
// gf24_mul.v - GoldenFloat24 (1/9/14, bias 255) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf24_mul (
    input  wire [23:0] a,
    input  wire [23:0] b,
    output reg  [23:0] result
);
    localparam [8:0] BIAS = 9'd255;
    localparam [8:0] EXP_MAX = 9'd511;

    wire             sign_a = a[23];
    wire [8:0]   exp_a  = a[22:14];
    wire [13:0]   mant_a = a[13:0];
    wire             sign_b = b[23];
    wire [8:0]   exp_b  = b[22:14];
    wire [13:0]   mant_b = b[13:0];

    wire is_zero_a = (exp_a==9'd0) && (mant_a==14'd0);
    wire is_zero_b = (exp_b==9'd0) && (mant_b==14'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==14'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==14'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=14'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=14'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [23:0] POS_INF = {1'b0, EXP_MAX, 14'd0};
    localparam [23:0] NEG_INF = {1'b1, EXP_MAX, 14'd0};
    localparam [23:0] QNAN    = {1'b1, EXP_MAX, 14'd1};

    reg signed [11:0] exp_product;
    reg [29:0] mant_product;          // 2M+2 = 30-bit product
    reg [14:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 23'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[29]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 12'sd1;
                norm  = {1'b1, mant_product[28:15]};
                guard = mant_product[14];
            end else begin                                 // [1,2): leading 1 at bit 28
                norm  = {1'b1, mant_product[27:14]};
                guard = mant_product[13];
            end
            if (guard) norm = norm + 15'd1;
            if (norm == 15'd0) exp_product = exp_product + 12'sd1;
            if (exp_product <= 0)
                result = {result_sign, 23'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[8:0], norm[13:0]};
        end
    end
endmodule
