// SPDX-License-Identifier: Apache-2.0
// gf32_mul.v - GoldenFloat32 (1/12/19, bias 2047) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf32_mul (
    input  wire [31:0] a,
    input  wire [31:0] b,
    output reg  [31:0] result
);
    localparam [11:0] BIAS = 12'd2047;
    localparam [11:0] EXP_MAX = 12'd4095;

    wire             sign_a = a[31];
    wire [11:0]   exp_a  = a[30:19];
    wire [18:0]   mant_a = a[18:0];
    wire             sign_b = b[31];
    wire [11:0]   exp_b  = b[30:19];
    wire [18:0]   mant_b = b[18:0];

    wire is_zero_a = (exp_a==12'd0) && (mant_a==19'd0);
    wire is_zero_b = (exp_b==12'd0) && (mant_b==19'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==19'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==19'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=19'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=19'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [31:0] POS_INF = {1'b0, EXP_MAX, 19'd0};
    localparam [31:0] NEG_INF = {1'b1, EXP_MAX, 19'd0};
    localparam [31:0] QNAN    = {1'b1, EXP_MAX, 19'd1};

    reg signed [14:0] exp_product;
    reg [39:0] mant_product;          // 2M+2 = 40-bit product
    reg [19:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 31'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[39]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 15'sd1;
                norm  = {1'b1, mant_product[38:20]};
                guard = mant_product[19];
            end else begin                                 // [1,2): leading 1 at bit 38
                norm  = {1'b1, mant_product[37:19]};
                guard = mant_product[18];
            end
            if (guard) norm = norm + 20'd1;
            if (norm == 20'd0) exp_product = exp_product + 15'sd1;
            if (exp_product <= 0)
                result = {result_sign, 31'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[11:0], norm[18:0]};
        end
    end
endmodule
