// SPDX-License-Identifier: Apache-2.0
// gf8_mul.v - GoldenFloat8 (1/3/4, bias 3) multiplier.
// Generated by fixes/gen_gf_mul.py - correct MSB-position template.
`default_nettype none
module gf8_mul (
    input  wire [7:0] a,
    input  wire [7:0] b,
    output reg  [7:0] result
);
    localparam [2:0] BIAS = 3'd3;
    localparam [2:0] EXP_MAX = 3'd7;

    wire             sign_a = a[7];
    wire [2:0]   exp_a  = a[6:4];
    wire [3:0]   mant_a = a[3:0];
    wire             sign_b = b[7];
    wire [2:0]   exp_b  = b[6:4];
    wire [3:0]   mant_b = b[3:0];

    wire is_zero_a = (exp_a==3'd0) && (mant_a==4'd0);
    wire is_zero_b = (exp_b==3'd0) && (mant_b==4'd0);
    wire is_inf_a  = (exp_a==EXP_MAX) && (mant_a==4'd0);
    wire is_inf_b  = (exp_b==EXP_MAX) && (mant_b==4'd0);
    wire is_nan_a  = (exp_a==EXP_MAX) && (mant_a!=4'd0);
    wire is_nan_b  = (exp_b==EXP_MAX) && (mant_b!=4'd0);
    wire result_sign = sign_a ^ sign_b;

    localparam [7:0] POS_INF = {1'b0, EXP_MAX, 4'd0};
    localparam [7:0] NEG_INF = {1'b1, EXP_MAX, 4'd0};
    localparam [7:0] QNAN    = {1'b1, EXP_MAX, 4'd1};

    reg signed [5:0] exp_product;
    reg [9:0] mant_product;          // 2M+2 = 10-bit product
    reg [4:0]  norm;                  // {leading1, M mantissa bits}
    reg          guard;

    always @(*) begin
        if (is_nan_a || is_nan_b)                 result = QNAN;
        else if (is_inf_a && is_zero_b)           result = QNAN;
        else if (is_inf_b && is_zero_a)           result = QNAN;
        else if (is_inf_a || is_inf_b)            result = result_sign ? NEG_INF : POS_INF;
        else if (is_zero_a || is_zero_b)          result = {result_sign, 7'd0};
        else begin
            exp_product  = $signed({ 3'b0, exp_a}) + $signed({ 3'b0, exp_b}) - $signed({ 3'b0, BIAS});
            mant_product = {1'b1, mant_a} * {1'b1, mant_b};
            if (mant_product[9]) begin                 // va*vb in [2,4): exp+1
                exp_product = exp_product + 6'sd1;
                norm  = {1'b1, mant_product[8:5]};
                guard = mant_product[4];
            end else begin                                 // [1,2): leading 1 at bit 8
                norm  = {1'b1, mant_product[7:4]};
                guard = mant_product[3];
            end
            if (guard) norm = norm + 5'd1;
            if (norm == 5'd0) exp_product = exp_product + 6'sd1;
            if (exp_product <= 0)
                result = {result_sign, 7'd0};
            else if (exp_product >= $signed({ 3'b0, EXP_MAX}))
                result = result_sign ? NEG_INF : POS_INF;
            else
                result = {result_sign, exp_product[2:0], norm[3:0]};
        end
    end
endmodule
